Repository rlaxoehd4234/Umbrella, pull requests merged in 2023-06, with the labels that each got.

#83 [FEAT] Schedule 을 List 형식으로 받는 것으로 일괄적으로 처리할 수 있게 수정
  src/main/java/com/umbrella/controller/WhenToMeetController.java
  src/main/java/com/umbrella/service/Impl/PostServiceImpl.java
  src/main/java/com/umbrella/service/Impl/WhenToMeetServiceImpl.java
  src/main/java/com/umbrella/service/WhenToMeetService.java
Labels: documentation

#84 [FEAT] Workspace 입장 시 ResponseDTO 값에 Board 와 Event 값 추가
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/WorkSpace/WorkSpace.java
  src/main/java/com/umbrella/dto/workspace/WorkspaceResponseDto.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/UserService.java
Labels: documentation

#85 [FEAT] Workspace 관련 추가
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/WorkSpace/WorkSpace.java
  src/main/java/com/umbrella/domain/WorkSpace/WorkspaceUser.java
  src/main/java/com/umbrella/domain/exception/WorkspaceExceptionType.java
  src/main/java/com/umbrella/dto/workspace/EventResponseDto.java
  src/main/java/com/umbrella/dto/workspace/WorkspaceResponseCreateDto.java
  src/main/java/com/umbrella/service/Impl/BoardServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/Impl/WhenToMeetServiceImpl.java
  src/main/java/com/umbrella/service/Impl/WorkSpaceServiceImpl.java
Labels: documentation

#88 [FEAT] add S3 image upload function
  .gradle/7.6/checksums/checksums.lock
  .gradle/7.6/checksums/md5-checksums.bin
  .gradle/7.6/checksums/sha1-checksums.bin
  .idea/misc.xml
  build.gradle
  src/main/java/com/umbrella/controller/S3Controller.java
  src/main/java/com/umbrella/domain/Comment/Comment.java
  src/main/java/com/umbrella/domain/PostImg/PostImg.java
  src/main/java/com/umbrella/dto/img/DeleteS3FileByFileNameDto.java
  src/main/java/com/umbrella/dto/img/ImgDto.java
  src/main/java/com/umbrella/service/Impl/AwsS3UploadServiceImpl.java
  src/main/java/com/umbrella/service/Impl/FileUploadService.java
  src/main/resources/application.yml
Labels: enhancement

#89 [FEAT] User 정보 업데이트 후 업데이트 된 정보를 응답값으로 반환하도록 변경
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/dto/user/UserResponseUpdateDto.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/UserService.java
Labels: documentation

#96 Terminal [FEAT] Workspace 입장 및 정보 반환 시 응답 값에 해당 Workspace 에 소속된 User 정보 같이 반환
  src/main/java/com/umbrella/dto/user/UserInWorkspaceDTO.java
  src/main/java/com/umbrella/dto/workspace/WorkspaceResponseDto.java
Labels: documentation

#97 [FIX] Workspace Validation Logic 에서 발생하던 버그 수정 & 오타 수정
  src/main/java/com/umbrella/service/Impl/BoardServiceImpl.java
  src/main/java/com/umbrella/service/Impl/WorkSpaceServiceImpl.java
Labels: bug

#99 [FIX] OAuth2 기능 사용할 수 있도록 authenticationEntryPoint 주석 처리함
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug

#104 [FIX] SendEmail 에 대한 SSL 과 CORS 설정 추가
  src/main/java/com/umbrella/config/mail/MailConfig.java
  src/main/java/com/umbrella/controller/MailController.java
Labels: bug

#108 [FIX] UserController 에 @CrossOrigin 추가
  src/main/java/com/umbrella/controller/UserController.java
Labels: bug, documentation

#109 [FIX] Spring MVC 와 Spring Security 를 동시에 사용할 경우, 양측 다 CORS 설정을 해둬야함
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/security/login/filter/JsonEmailPasswordAuthenticationFilter.java
Labels: bug, documentation

#115 [REFACTOR] Login 처리를 Filter 단이 아닌 Service 로직에서 진행하도록 변경
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/exception/UserExceptionType.java
  src/main/java/com/umbrella/dto/user/UserResponseLoginDto.java
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/filter/JsonEmailPasswordAuthenticationFilter.java
  src/main/java/com/umbrella/security/login/handler/LoginFailureHandler.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/UserService.java
Labels: bug, documentation

#116 [REFACTOR] Workspace 목록 반환 값에 id 값 추가
  src/main/java/com/umbrella/dto/workspace/WorkspaceUserListResponseDto.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/LoginService.java
Labels: bug, documentation

#119 [FIX] WebConfig
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
  src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
  src/main/java/com/umbrella/service/Impl/WorkSpaceServiceImpl.java
Labels: bug, documentation

#120 [FIX] 비밀번호 찾기 로직 JWT 필터에서 제외
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
Labels: bug, documentation

#121 [FIX] 찐찐막 CORS 수정
  src/main/java/com/umbrella/config/mail/WebConfig.java
Labels: bug, documentation

#122 [FIX] Cookie 설정 Https OFF 로 해둠
  src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
Labels: bug, documentation

#123 [FIX] CookieUtil addCookie HttpOnly false 로 변경
  src/main/java/com/umbrella/security/utils/CookieUtil.java
Labels: bug, documentation

#124 [REFACTOR] WebConfig 에 헤더 허용 값 추가
  src/main/java/com/umbrella/config/mail/WebConfig.java
Labels: bug, documentation

#125 [REFACTOR] SecurityConfig CORS 추가
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug, documentation

#126 [REFACTOR] CORS 설정 추가
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug, documentation

#127 [FIX] PreFlightRequest 무시하는 로직 추가
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/controller/MailController.java
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug, documentation

#129 [FIX] AllowedOrigins -> AllowedOriginPatterns 로 변경
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug, documentation

#133 [REFACTOR] RefreshToken 인증 기능 임시 제거
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umbrella/security/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/main/java/com/umbrella/service/JwtService.java
Labels: bug, documentation

#134 [FIX] withCredentials 옵션 false 로 변경함
  src/main/java/com/umbrella/config/mail/WebConfig.java
  src/main/java/com/umbrella/security/SecurityConfig.java
Labels: bug, documentation
