Repository rlaxoehd4234/Umbrella, pull requests merged in 2023-04, with the labels that each got.

#21 Feat comment
  .idea/misc.xml
  src/main/java/com/umbrella/domain/Comment/CommentRepository.java
  src/main/java/com/umbrella/domain/Post/PostRepository.java
  src/main/java/com/umbrella/dto/comment/CommentRequestDto.java
  src/main/java/com/umbrella/dto/comment/CommentResponseDto.java
  src/main/java/com/umbrella/service/CommentService.java
  src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
Labels: enhancement

#32 [FEAT] Comment Service edit Controller
  src/main/java/com/umbrella/controller/CommentController.java
  src/main/java/com/umbrella/dto/comment/CommentPageRequestDto.java
  src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
Labels: enhancement

#33 [FEAT] Add a Heart function
  src/main/java/com/umbrella/controller/PostHeartController.java
  src/main/java/com/umbrella/domain/Heart/PostHeart.java
  src/main/java/com/umbrella/domain/Heart/PostHeartRepository.java
  src/main/java/com/umbrella/domain/Post/Post.java
  src/main/java/com/umbrella/domain/exception/PostExceptionType.java
  src/main/java/com/umbrella/dto/Heart/HeartRequestDto.java
  src/main/java/com/umbrella/service/HeartService.java
  src/main/java/com/umbrella/service/Impl/HeartServiceImpl.java
Labels: enhancement

#40 Terminal [FEAT & FIX] JwtExceptionFilter 추가 & JWT 인증 방식 수정
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umbrella/security/login/filter/JwtExceptionFilter.java
  src/main/java/com/umbrella/security/utils/RoleUtil.java
  src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
  src/main/java/com/umbrella/service/JwtService.java
  src/main/resources/application-jwt.yml
  src/main/resources/application-oauth2.yml
  src/main/resources/application.yml
  src/test/java/com/umbrella/project_umbrella/controller/UserControllerTest.java
  src/test/java/com/umbrella/project_umbrella/jwt/JwtAuthenticationProcessingFilterTest.java
Labels: enhancement

#41 [REFACTOR] 사용하지 않는 TEST Method 에 @Disabeld 추가
  src/test/java/com/umbrella/project_umbrella/jwt/JwtServiceTest.java
  src/test/java/com/umbrella/project_umbrella/service/UserServiceTest.java
Labels: enhancement

#42 [FIX] UserController 의 getInfo 수행 시 에러가 발생하여 Http Method 를 변경함
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/User/User.java
  src/main/java/com/umbrella/dto/user/UserInfoDto.java
  src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
  src/main/java/com/umbrella/dto/user/UserUpdateDto.java
  src/main/java/com/umbrella/dto/user/WithdrawUserDto.java
  src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/test/java/com/umbrella/project_umbrella/controller/UserControllerTest.java
Labels: bug, enhancement

#43 [REFACTOR] User 와 관련된 ExceptionHandling 을 대부분의 로직에 추가함
  src/main/java/com/umbrella/constant/Gender.java
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/exception/UserException.java
  src/main/java/com/umbrella/domain/exception/UserExceptionType.java
  src/main/java/com/umbrella/dto/user/UpdatePasswordDto.java
  src/main/java/com/umbrella/dto/user/UserRequestLoginDto.java
  src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
  src/main/java/com/umbrella/dto/user/UserUpdateDto.java
  src/main/java/com/umbrella/dto/user/WithdrawUserDto.java
  src/main/java/com/umbrella/exception/ExceptionAdvice.java
  src/main/java/com/umbrella/exception/ExceptionDto.java
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/filter/JwtExceptionFilter.java
  src/main/java/com/umbrella/security/login/handler/LoginFailureHandler.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/security/login/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/umbrella/security/oAuth2/factory/OAuth2UserInfoFactory.java
  src/main/java/com/umbrella/security/userDetails/UserContext.java
  src/main/java/com/umbrella/service/Impl/CustomOAuth2UserServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/test/java/com/umbrella/project_umbrella/controller/UserControllerTest.java
  src/test/java/com/umbrella/project_umbrella/jwt/JwtAuthenticationProcessingFilterTest.java
  src/test/java/com/umbrella/project_umbrella/service/UserServiceTest.java
Labels: enhancement

#44 [REFACTOR] ExceptionAdvice 관련 리팩토링
  src/main/java/com/umbrella/exception/ExceptionAdvice.java
Labels: enhancement

#45 [REFACTOR] security package 의 OAuth2 를 제외한 나머지 코드들 리팩토링
  src/main/java/com/umbrella/security/login/filter/JsonEmailPasswordAuthenticationFilter.java
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umbrella/security/login/filter/JwtExceptionFilter.java
  src/main/java/com/umbrella/security/login/handler/LoginFailureHandler.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/security/userDetails/UserContext.java
Labels: enhancement

#46 [REFACTOR] 코드 리팩토링
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/exception/UserExceptionType.java
  src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
  src/main/java/com/umbrella/exception/ExceptionAdvice.java
Labels: enhancement

#48 Feat Chat 기능 일부 개발
  src/main/java/com/umbrella/Config/SocketConfig/WebSocketMessageBrokerConfig.java
  src/main/java/com/umbrella/controller/ChatController.java
  src/main/java/com/umbrella/controller/ChatRoomController.java
  src/main/java/com/umbrella/domain/Chat/ChatMessage.java
  src/main/java/com/umbrella/domain/Chat/ChatMessageRepository.java
  src/main/java/com/umbrella/domain/Chat/ChatRoom.java
  src/main/java/com/umbrella/domain/Chat/ChatRoomJoin.java
  src/main/java/com/umbrella/domain/Chat/ChatRoomJoinRepository.java
  src/main/java/com/umbrella/domain/Chat/ChatRoomRepository.java
  src/main/java/com/umbrella/dto/chat/ChatDto.java
  src/main/java/com/umbrella/dto/chat/ChatMessageLogDto.java
  src/main/java/com/umbrella/dto/chat/ChatRoomDto.java
  src/main/java/com/umbrella/dto/chat/ChatRoomsResponseDto.java
  src/main/java/com/umbrella/service/Impl/ChatRoomServiceImpl.java
  src/main/java/com/umbrella/service/Impl/ChatServiceImpl.java
  src/main/java/com/umbrella/service/Impl/CommentServiceImpl.java
Labels: enhancement

#50 [FEAT] UserExceptionType IMPOSSIBLE_AGE_ERROR 추가
  src/main/java/com/umbrella/domain/exception/UserExceptionType.java
  src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umbrella/service/Impl/CustomOAuth2UserServiceImpl.java
Labels: enhancement

#51 [FEAT] OAuth2 로그인 성공 시 AccessToken, RefreshToken 발급
  src/main/java/com/umbrella/domain/Chat/ChatRoom.java
  src/main/java/com/umbrella/exception/ExceptionAdvice.java
  src/main/java/com/umbrella/exception/GlobalExceptionType.java
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/security/login/handler/OAuth2LoginSuccessHandler.java
Labels: enhancement

#57 [REFACTOR] warnings 가 나타난 부분들 수정할 수 있는 거 수정함
  src/main/java/com/umbrella/controller/UserController.java
  src/main/java/com/umbrella/domain/exception/PostExceptionType.java
  src/main/java/com/umbrella/domain/exception/UserException.java
  src/main/java/com/umbrella/domain/exception/UserExceptionType.java
  src/main/java/com/umbrella/dto/user/UpdatePasswordDto.java
  src/main/java/com/umbrella/dto/user/UserRequestLoginDto.java
  src/main/java/com/umbrella/dto/user/UserRequestSignUpDto.java
  src/main/java/com/umbrella/dto/user/UserUpdateDto.java
  src/main/java/com/umbrella/dto/user/WithdrawUserDto.java
  src/main/java/com/umbrella/security/SecurityConfig.java
  src/main/java/com/umbrella/security/login/cookie/CookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/umbrella/security/login/filter/JsonEmailPasswordAuthenticationFilter.java
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/main/java/com/umbrella/security/login/handler/LoginFailureHandler.java
  src/main/java/com/umbrella/security/login/handler/LoginSuccessJWTProvideHandler.java
  src/main/java/com/umbrella/security/login/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/umbrella/security/login/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/umbrella/security/utils/CookieUtil.java
  src/main/java/com/umbrella/service/Impl/JwtServiceImpl.java
  src/main/java/com/umbrella/service/Impl/LoginServiceImpl.java
  src/main/java/com/umbrella/service/Impl/UserServiceImpl.java
  src/test/java/com/umbrella/project_umbrella/jwt/JwtAuthenticationProcessingFilterTest.java
Labels: enhancement

#58 [FIX] UserController TEST 코드 전부 실패한 원인을 발견, 수정함
  src/main/java/com/umbrella/security/login/filter/JwtAuthenticationProcessingFilter.java
  src/test/java/com/umbrella/project_umbrella/controller/UserControllerTest.java
Labels: bug
